// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotDrKAkGqCgiSqnhIHjPxZEhGk8Oc5nI',
    appId: '1:292759101279:web:113f117e5c54a5d52760ea',
    messagingSenderId: '292759101279',
    projectId: 'myprofileapp-5c830',
    authDomain: 'myprofileapp-5c830.firebaseapp.com',
    storageBucket: 'myprofileapp-5c830.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADmrYkTkIy57phxcnC2YSPYUWjomoR-Zo',
    appId: '1:292759101279:android:2ed59563974b32102760ea',
    messagingSenderId: '292759101279',
    projectId: 'myprofileapp-5c830',
    storageBucket: 'myprofileapp-5c830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTVE1tWQr8DHZeo2gY5QoJgTGhpgGvVLA',
    appId: '1:292759101279:ios:1264f78b2bd6b60d2760ea',
    messagingSenderId: '292759101279',
    projectId: 'myprofileapp-5c830',
    storageBucket: 'myprofileapp-5c830.appspot.com',
    iosClientId: '292759101279-8c9bic7feemj4r578i6vp36l40vfd875.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProfileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTVE1tWQr8DHZeo2gY5QoJgTGhpgGvVLA',
    appId: '1:292759101279:ios:1264f78b2bd6b60d2760ea',
    messagingSenderId: '292759101279',
    projectId: 'myprofileapp-5c830',
    storageBucket: 'myprofileapp-5c830.appspot.com',
    iosClientId: '292759101279-8c9bic7feemj4r578i6vp36l40vfd875.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProfileApp',
  );
}
